### ISSUE TITLE
缺少暗色模式

### ISSUE THREAD

**Issue by Misaka-0x447f** [littlecxm/arcademap-issue#2]
我来增加 issue 数量了（

**Comment by littlecxm** [comment]
因为网页是blade，所以大体相当于一个没有前端的状态，即只能等待页面全部加载后js才能判别
如果强行加入的话只能非常的瞎眼。

**Comment by Misaka-0x447f** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
判断颜色模式主要靠的是 css media query 而不是 js，以及 js 判断接口也是依赖 css 的。所以不会有这种问题。浏览器会等到 css 加载完成才显示。

**Comment by Misaka-0x447f** [comment]
另外在一般的情况下，只要在程序开始执行的时候判断了深色模式，就不会出现闪屏的情况，因为 js 开始执行的时候浏览器一般还处于 painting 的状态

**Comment by littlecxm** [comment]
![image](https://user-images.githubusercontent.com/16154023/86483758-4f7c4400-bd87-11ea-8dab-06b924e474ff.png)
这样怎么样

**Comment by pboymt** [comment]
暂时没有提供的话可以用Dark Reader插件，Edge、Chrome和Firefox上都是热门插件。黑暗模式化可以参考它们的逻辑。

**Comment by littlecxm** [comment]
done with new version 2.0
