### ISSUE TITLE
[Feat] 在机厅名称下附带机台标志

### ISSUE THREAD

**Issue by Yushu2606** [littlecxm/arcademap-issue#21]
多个同种机台可以用`*X`标注

**Comment by littlecxm** [comment]
没太明白这是个什么需求

**Comment by Yushu2606** [comment]
> 没太明白这是个什么需求

就是不用点进机厅就能看到有哪些机台

**Comment by littlecxm** [comment]
> > 没太明白这是个什么需求
> 
> 就是不用点进机厅就能看到有哪些机台

大概说说希望展示的地方？因为机厅页面有好几个展示的位置
