### ISSUE TITLE
[Bug] 交通路线换行错误

### ISSUE THREAD

**Issue by Dragon-ts** [littlecxm/arcademap-issue#25]
**描述错误**
交通路线换行错误

**复现**
1. 编辑店铺信息
2. 编辑交通路线
3. 保存预览
4. 自动换行错误

**屏幕截图**
![我是图片](https://github.com/littlecxm/arcademap-issue/assets/106637358/b1bcd2dd-f470-4cc4-99bf-1fd2b0abd55e)

**其他**
（此处添加有关该问题的任何其他内容。）

**Comment by littlecxm** [comment]
已经修复
<img width="353" alt="image" src="https://github.com/littlecxm/arcademap-issue/assets/16154023/e70cd0c0-8913-4507-b733-ccf60c4341d4">
