### ISSUE TITLE
[Feat] 删除店铺申请撤回

### ISSUE THREAD

**Issue by redcapcord** [littlecxm/arcademap-issue#28]
一开始找今天没找到地图上面的机厅（欢乐故事（昆明新西南店）），看到去那一层的电梯封住了，而且封起来装修了。我就以为店铺关闭了。但后面找到一个隐蔽的垂直电梯才下到机厅（欢乐故事（昆明新西南店））。希望能加个撤回功能😭😭😭

**Comment by littlecxm** [comment]
现在有店铺撤回功能，联系管理员操作可进行撤回

**Comment by STARIFI** [comment]
> 现在有店铺撤回功能，联系管理员操作可进行撤回

如何联系管理员

**Comment by littlecxm** [comment]
> > 现在有店铺撤回功能，联系管理员操作可进行撤回
> 
> 如何联系管理员

加入反馈群联系群管理员
